### ISSUE TITLE
Cannot execute the command "Insert feature to point"

### ISSUE THREAD

**Issue by nlpguyz** [monikaUPF/modularProsodyTagger#2]
Hi,

The scripts appear to be very useful and interesting. However, I ran into a problem with mod01.praat. Here is the error:

Command "Insert feature to point:" not available for current selection.
Script line 82 not performed or completed:
« Insert feature to point: 2, p, "int", int_peak$ »
Please change something in the command window “Run script: Parameters”, or click Cancel in that window.

Can you please let me know what I missed? Thank you!

**Comment by monikaUPF** [comment]
Hi,

Thank you for your interest. The first thing you need to make sure is that you are using the extension of praat for feature annotation. These scripts do not run on standard praat. We modified the program so that it can annotate features. The praat extension is available in my github as well as in the TALN-UPF github. The software is self executable as Praat, and it only runs under Linux for now. There is also an online demo (http://kristina.taln.upf.edu/praatweb/) where you can upload your wav files, visualize and download the result as TextGrid, that can be opened in standard Praat. You can also find further information in our publications:
- on Praat on the Web https://repositori.upf.edu/handle/10230/27756
- on the prosody tagger https://repositori.upf.edu/handle/10230/27755
I hope that solves your issue. Do not hesitate to contact me if you have any further questions.

Best,
Monika

**Comment by nlpguyz** [comment]
Thanks Monika for answering my question. It solved my issue like charm. Your research papers are very helpful too. Thanks!

**Comment by monikaUPF** [comment]
Thanks for your interest. Cheers!
